pub(crate) mod by_device_token;
pub(crate) mod by_password;
pub(crate) mod smsru_phone_query;
pub(crate) mod delete_token;
pub(crate) mod send_warn_mail;
pub(crate) mod by_tel_call;
pub(crate) mod smsru_cf_query;
pub(crate) mod registration;
pub(crate) mod validate_fields;