// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { Phone } from "./Phone";
import type { SessionUserToken } from "./SessionUserToken";
import type { TextInfo } from "./TextInfo";

export type AuthStep = { "Loading": Record<string, never> } | { "Init": Record<string, never> } | { "SuccessFull": { session_user_token: SessionUserToken, } } | { "SuccessShort": Record<string, never> } | { "CallIn": { phone: Phone, external_id: string, text: TextInfo, } } | { "NeedPassword": { text: TextInfo, } } | { "NeedRegistration": { text: TextInfo, } } | { "TryLater": { text: TextInfo, } } | { "TokenDevicePairMiss": { token: BoxUuid, text: TextInfo, } };
