// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompInn } from "./CompInn";
import type { Kpp } from "./Kpp";
import type { PersInn } from "./PersInn";

export type PasswordDataShort = { nick: string, password: string, pers_inn: PersInn, comp_inn: CompInn, kpp: Kpp, };
