// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Inn } from "./Inn";
import type { Kpp } from "./Kpp";

export type PasswordDataShort = { nick: string, password: string, pers_inn: Inn, comp_inn: Inn, kpp: Kpp, };
