// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { DateTime } from "./DateTime";
import type { Inn } from "./Inn";
import type { PersonMetadata } from "./PersonMetadata";

export type Person = { pers_id: BoxUuid, inn: Inn, metadata: PersonMetadata, last_update: DateTime, };
