back_api_url = "http://127.0.0.1:8080"

[network]
inst_conn_timeout = 1
inst_tot_timeout = 2
inst_request_interval = 1
inst_retries = 3
inst_poll_intervals = 1

std_conn_timeout = 5
std_tot_timeout = 10
std_request_interval = 2
std_retries = 5
std_poll_intervals = 4

rel_conn_timeout = 10
rel_tot_timeout = 60
rel_request_interval = 3
rel_retries = 3
rel_poll_intervals = 10

[sqlite_options]
max_connections = 5
duration = 3


[own_company]
own_ras_acc = "40802810629370001827"
own_inn = "161101510882"
own_bic = "042202824"
own_comp_id = "1"
own_user_id = "1"