// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthInfo } from "./AuthInfo";
import type { AuthStep } from "./AuthStep";
import type { ExternalDeviceData } from "./ExternalDeviceData";
import type { NickData } from "./NickData";
import type { PasswordDataClientShort } from "./PasswordDataClientShort";
import type { RegFilesPathData } from "./RegFilesPathData";
import type { RegInitData } from "./RegInitData";

export type AuthTs = { "authInfo": AuthInfo } | { "authStep": AuthStep } | { "externalDeviceData": ExternalDeviceData } | { "nickData": NickData } | { "regFilesPathData": RegFilesPathData } | { "regInitData": RegInitData } | { "passwordDataClientShort": PasswordDataClientShort };
