// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdrWrap } from "./AdrWrap";
import type { BranchType } from "./BranchType";
import type { CompInn } from "./CompInn";
import type { DadaCompName } from "./DadaCompName";
import type { Date } from "./Date";
import type { IsCompActive } from "./IsCompActive";
import type { Kpp } from "./Kpp";
import type { MainManager } from "./MainManager";
import type { Ogrn } from "./Ogrn";
import type { Okfs } from "./Okfs";
import type { Okogu } from "./Okogu";
import type { Okpo } from "./Okpo";
import type { Oktmo } from "./Oktmo";
import type { Okved } from "./Okved";
import type { OpfData } from "./OpfData";
import type { Phone } from "./Phone";
import type { RasBicAcc } from "./RasBicAcc";
import type { String3_129 } from "./String3_129";

export type CtrprtyMetadata = { kpp: Kpp | null, main_manager: MainManager | null, branch_type: BranchType | null, type: string | null, is_active: IsCompActive | null, opf: OpfData | null, comp_name: DadaCompName | null, inn: CompInn | null, ogrn: Ogrn | null, okpo: Okpo | null, oktmo_company: Oktmo | null, okogu: Okogu | null, okfs: Okfs | null, okved: Okved | null, ogrn_date_dadata: bigint | null, address: AdrWrap | null, e_mail: String3_129 | null, phone: Phone | null, bank_acc: Array<RasBicAcc>, ogrn_date_date: Date | null, };
