// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanyName } from "./CompanyName";

export type DadaCompName = { full_egrul_name: CompanyName | null, short_egrul_name: CompanyName | null, };
