// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delegate } from "./Delegate";
import type { DelegateType } from "./DelegateType";

export type DelegateWrap = { "@ТипПред": DelegateType, Пред: Delegate, };
