// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignOrg } from "./ForeignOrg";
import type { IpPrincipal } from "./IpPrincipal";
import type { PersonPrincipal } from "./PersonPrincipal";
import type { RussOrganization } from "./RussOrganization";

export type InitPrincipal = { organization: RussOrganization | null, foreign_organization: ForeignOrg | null, ip: IpPrincipal | null, person: PersonPrincipal | null, };
