// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IrrevocablePoaRedelegationType } from "./IrrevocablePoaRedelegationType";
import type { IrrevocablePoaRevocationCondition } from "./IrrevocablePoaRevocationCondition";
import type { String1_1000 } from "./String1_1000";

export type IrrevocablePoa = { "@ПрПерБезДов": IrrevocablePoaRedelegationType, "@УслОтзыва": IrrevocablePoaRevocationCondition, revocation_condition_text: String1_1000 | null, };
