// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { HomeMchdPower } from "./HomeMchdPower";
import type { MchdInfo } from "./MchdInfo";
import type { String1_255 } from "./String1_255";

export type MchdStep = { "BTBMchd": { text: MchdInfo, } } | { "FnsMchd": { text: MchdInfo, } } | { "HomeMchd": { text: MchdInfo, } } | { "LendMchd": { text: MchdInfo, } } | { "Loading": { text: MchdInfo, } } | { "SaveXmlDocFiles": { doc_name: String1_255, doc_file: Array<number>, xml_name: String1_255, xml_file: Array<number>, text: MchdInfo, } } | { "ShowPowers": { fns: Array<HomeMchdPower>, btb: Array<HomeMchdPower>, home: Array<HomeMchdPower>, text: MchdInfo, } } | { "SuccessRegisterMchd": { guide: BoxUuid, text: MchdInfo, } } | { "TryLater": { text: MchdInfo, } } | { "WrongData": { text: MchdInfo, } };
