// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpfCode } from "./OpfCode";

export type OpfData = { full_opf: string | null, short_opf: string | null, opf_code: OpfCode | null, };
