// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { RussDocumCode } from "./RussDocumCode";
import type { String1_25 } from "./String1_25";
import type { String1_4000 } from "./String1_4000";
import type { String7_7 } from "./String7_7";

export type PersonDocum = { "@КодВидДок": RussDocumCode, "@СерНомДок": String1_25, "@ДатаДок": Date, issued_by: String1_4000 | null, issued_code: String7_7 | null, exp_date: Date | null, };
