// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressChoice } from "./AddressChoice";
import type { BoxUuid } from "./BoxUuid";
import type { Region } from "./Region";

export type PostalAddress = { "@Регион": Region, fias_id: BoxUuid | null, address: AddressChoice | null, };
