// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Principal } from "./Principal";
import type { PrincipalIdentity } from "./PrincipalIdentity";

export type PrincipalWrap = { "@ТипДоверит": PrincipalIdentity, Доверит: Principal, };
