// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignOrgPrincipal } from "./ForeignOrgPrincipal";
import type { IpPrincipal } from "./IpPrincipal";
import type { PersonPrincipal } from "./PersonPrincipal";
import type { RussOrgPrincipal } from "./RussOrgPrincipal";

export type Principal = { russian_org: RussOrgPrincipal | null, foreign_org: ForeignOrgPrincipal | null, ip: IpPrincipal | null, person: PersonPrincipal | null, };
