// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flag } from "./Flag";
import type { RootManager } from "./RootManager";
import type { RussOrganization } from "./RussOrganization";

export type RussOrgPrincipal = { "@ЕИОУК": Flag, "@ЕИОФЛ": Flag, "@ЕИОИП": Flag, СвРосОрг: RussOrganization, ЛицоБезДов: Array<RootManager>, };
