// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignOrgPrincipal } from "./ForeignOrgPrincipal";
import type { IpPrincipal } from "./IpPrincipal";
import type { RedelegatePerson } from "./RedelegatePerson";
import type { RedelegaterFilial } from "./RedelegaterFilial";
import type { RussOrgPrincipal } from "./RussOrgPrincipal";

export type SubPrincipalInfo = { russian_organization: RussOrgPrincipal | null, ip: IpPrincipal | null, person: RedelegatePerson | null, filial: RedelegaterFilial | null, foreign_organizetioan: ForeignOrgPrincipal | null, };
