// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegateType } from "./DelegateType";
import type { SubPrincipalInfo } from "./SubPrincipalInfo";

export type SubPrincipal = { "@ТипПерПолн": DelegateType, ПередПолн: SubPrincipalInfo, };
