// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fio } from "./Fio";
import type { String1_255 } from "./String1_255";
import type { String3_8 } from "./String3_8";

export type ActingNotary = { "@Должность": String1_255, "@РегНомНот": String3_8, ФИОВриоНот: Fio, };
