// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { String1_1000 } from "./String1_1000";

export type AddressChoice = { "АдрРФ": String1_1000 } | { "ФИАСАдрРФ": String1_1000 };
