// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthInfo } from "./AuthInfo";
import type { Phone } from "./Phone";
import type { SessionUserToken } from "./SessionUserToken";

export type AuthStep = { "CallIn": { phone: Phone, external_id: string, text: AuthInfo, } } | { "CallInWaiting": { text: AuthInfo, } } | { "Loading": { text: AuthInfo, } } | { "NickName": { text: AuthInfo, } } | { "Password": { text: AuthInfo, } } | { "RegisterStep1": { text: AuthInfo, } } | { "RegisterStep2": { text: AuthInfo, } } | { "SuccessFull": { session_user_token: SessionUserToken, } } | { "SuccessShort": Record<string, never> } | { "TokenDevicePairMiss": { text: AuthInfo, } } | { "TryLater": { text: AuthInfo, } };
