// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Contract } from "./Contract";

export type ContractOption = { current: Contract | null, contracts: Array<Contract>, };
