// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignOrg } from "./ForeignOrg";
import type { IpPrincipal } from "./IpPrincipal";
import type { RussOrganization } from "./RussOrganization";
import type { WrapPerson } from "./WrapPerson";

export type Delegate = { СведОрг: RussOrganization | null, СведИП: IpPrincipal | null, СведФизЛ: WrapPerson | null, СведФилиал: RussOrganization | null, СведИО: ForeignOrg | null, };
