// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignOrg } from "./ForeignOrg";
import type { Ip } from "./Ip";
import type { JuridicalWrapPerson } from "./JuridicalWrapPerson";
import type { RussOrganization } from "./RussOrganization";

export type Delegate = { СведОрг: RussOrganization | null, СведИП: Ip | null, СведФизЛ: JuridicalWrapPerson | null, СведФилиал: RussOrganization | null, СведИО: ForeignOrg | null, };
