// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MchdPower } from "./MchdPower";
import type { PowerCommonType } from "./PowerCommonType";
import type { PowerType } from "./PowerType";
import type { RedelegatePowerLossType } from "./RedelegatePowerLossType";
import type { String1_10000 } from "./String1_10000";

export type DelegatePowers = { "@ТипПолн": PowerType, "@ПрСовмПолн": PowerCommonType, "@ПрУтрПолн": RedelegatePowerLossType | null, ТекстПолн: String1_10000 | null, mchd_powers: Array<MchdPower>, };
