// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { String1_1000 } from "./String1_1000";
import type { String1_120 } from "./String1_120";

export type DirectAuthorityDoc = { name: String1_120 | null, issue_date: Date | null, issued_by: String1_1000 | null, cert_info: String1_1000 | null, };
