// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";

export type ExternalDeviceData = { external_id: string, device_id: BoxUuid, };
