// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompInn } from "./CompInn";
import type { Digits3_3 } from "./Digits3_3";
import type { Kpp } from "./Kpp";
import type { Phone } from "./Phone";
import type { PostalAddress } from "./PostalAddress";
import type { PrincipalNotarialStatus } from "./PrincipalNotarialStatus";
import type { String11_11 } from "./String11_11";
import type { String1_1000 } from "./String1_1000";
import type { String1_255 } from "./String1_255";
import type { String1_80 } from "./String1_80";
import type { String3_129 } from "./String3_129";

export type ForeignOrg = { "@СтУчНД": PrincipalNotarialStatus | null, "@НаимИО": String1_1000, "@ИННЮЛ": CompInn | null, "@КПП": Kpp | null, "@НЗА": String11_11 | null, "@СтрРег": Digits3_3 | null, "@НаимРегОрг": String1_255 | null, "@РегНомер": String1_80 | null, "@КодНПРег": String1_80 | null, "@КонтактТлф": Phone | null, "@АдрЭлПочт": String3_129 | null, "@АдрСтрРег": String1_1000 | null, АдрМНФакт: PostalAddress | null, };
