// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompInn } from "./CompInn";
import type { Email } from "./Email";
import type { FirstName } from "./FirstName";
import type { Kpp } from "./Kpp";
import type { MidName } from "./MidName";
import type { PersInn } from "./PersInn";
import type { Phone } from "./Phone";
import type { Snils } from "./Snils";
import type { String1_50 } from "./String1_50";
import type { SurName } from "./SurName";

export type IngoingData = { nick: String1_50, sur_name: SurName, first_name: FirstName, mid_name: MidName | null, pers_inn: PersInn, snils: Snils, comp_inn: CompInn, kpp: Kpp, phone: Phone, email: Email, };
