// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InitFiles = { docName: string, docFile: Array<number>, jsonName: string, jsonFile: Array<number>, };
