// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitPrincipal } from "./InitPrincipal";
import type { PrincipalIdentity } from "./PrincipalIdentity";

export type InitPrincipalWrap = { "@ТипДоверит": PrincipalIdentity, ДоверитПерв: InitPrincipal, };
