// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignOrg } from "./ForeignOrg";
import type { Ip } from "./Ip";
import type { PrincipalPerson } from "./PrincipalPerson";
import type { RussOrganization } from "./RussOrganization";

export type InitPrincipal = { РосОргДовер: RussOrganization | null, ИнОргДовер: ForeignOrg | null, ИПДовер: Ip | null, ФЛДовер: PrincipalPerson | null, };
