// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectAuthorityDoc } from "./DirectAuthorityDoc";
import type { Ogrn } from "./Ogrn";
import type { ParticipantStatus } from "./ParticipantStatus";
import type { PersInn } from "./PersInn";
import type { PersonMchd } from "./PersonMchd";
import type { Snils } from "./Snils";
import type { String1_1000 } from "./String1_1000";

export type Ip = { "@СтУчНД": ParticipantStatus | null, "@НаимИП": String1_1000 | null, "@ОГРНИП": Ogrn, "@ИННФЛ": PersInn, "@СНИЛС": Snils, ДокПдтв: DirectAuthorityDoc | null, СведФЛ: PersonMchd, };
