// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ip } from "./Ip";
import type { JuridicalWrapPerson } from "./JuridicalWrapPerson";
import type { ManagementType } from "./ManagementType";
import type { PrimeManagerOrg } from "./PrimeManagerOrg";

export type LegalRep = { "@ПолнЮЛ": ManagementType, СВЮЛ: PrimeManagerOrg | null, СвФЛ: JuridicalWrapPerson | null, СвИП: Ip | null, };
