// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MainManager = { main_manager_fio: string | null, manager_title: string | null, };
