// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoaLimitations } from "./PoaLimitations";
import type { String1_255 } from "./String1_255";
import type { String6_255 } from "./String6_255";

export type MchdPower = { powers_mnemonic: String6_255 | null, "@КодПолн": String6_255, "@НаимПолн": String1_255, poa_limitations: Array<PoaLimitations>, };
