// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MchdInfo } from "./MchdInfo";
import type { MchdPower } from "./MchdPower";
import type { String1_255 } from "./String1_255";

export type MchdStep = { "HomeMchd": { text: MchdInfo, } } | { "LendMchd": { text: MchdInfo, } } | { "Loading": { text: MchdInfo, } } | { "ShowPowers": { tax_powers: Array<MchdPower>, home_powers: Array<MchdPower>, test: MchdInfo, } } | { "Success": { doc_name: String1_255, doc_file: Array<number>, xml_name: String1_255, xml_file: Array<number>, text: MchdInfo, } } | { "TaxMchd": { text: MchdInfo, } } | { "TryLater": { text: MchdInfo, } } | { "WrongData": { text: MchdInfo, } };
