// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { String1_50 } from "./String1_50";

export type NickData = { nick_names: Array<String1_50>, };
