// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActingNotary } from "./ActingNotary";
import type { Flag } from "./Flag";
import type { Notary } from "./Notary";
import type { RubF } from "./RubF";
import type { Signature } from "./Signature";
import type { String1_250 } from "./String1_250";
import type { String1_2500 } from "./String1_2500";
import type { String1_255 } from "./String1_255";

export type NotarialCertification = { "@МестоДовер": String1_250, "@НапрДокДовЕПГУ": Flag | null, "@НапрДокПовЕПГУ": Flag | null, "@НапрДокЗвлФНП": Flag | null, "@НапрДокПовФНП": Flag | null, "@УплНотДейст": RubF, "@ЛьготаСум": RubF | null, "@ДрИнфСист": String1_255 | null, "@ДрСпосВыд": String1_255 | null, "@ДопСвНотДовер": String1_2500 | null, ИнСвУдНадпис: String1_2500 | null, СвНотДейств: Notary, ПодпРукопис: Array<Signature>, ВриоНот: ActingNotary | null, };
