// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActingNotary } from "./ActingNotary";
import type { BoxUuid } from "./BoxUuid";
import type { Date } from "./Date";
import type { InitPrincipalTypeShort } from "./InitPrincipalTypeShort";
import type { InitPrincipalWrap } from "./InitPrincipalWrap";
import type { Notary } from "./Notary";
import type { PoaLegalForm } from "./PoaLegalForm";
import type { String1_28 } from "./String1_28";
import type { String1_50 } from "./String1_50";

export type OriginalPoa = { "@ПрДовер": InitPrincipalTypeShort, "@ФормДовер": PoaLegalForm, "@ДатаВыдДовер": Date, "@СрокДейст": Date, "@ВнНомДоверПерв": String1_50 | null, "@ВнНомДоверN": String1_50 | null, "@НомДоверПерв": BoxUuid | null, "@НомДоверN": BoxUuid | null, "@НомРНДПерв": String1_28 | null, "@НомРНДN": String1_28 | null, origin_principal: Array<InitPrincipalWrap>, СвНотДейств: Notary | null, ВриоНот: ActingNotary | null, };
