// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActingNotary } from "./ActingNotary";
import type { BoxUuid } from "./BoxUuid";
import type { Date } from "./Date";
import type { InitPrincipalTypeShort } from "./InitPrincipalTypeShort";
import type { InitPrincipalWrap } from "./InitPrincipalWrap";
import type { Notary } from "./Notary";
import type { PoaLegalForm } from "./PoaLegalForm";
import type { String1_28 } from "./String1_28";
import type { String1_50 } from "./String1_50";

export type OriginalPoa = { "@ПрДовер": InitPrincipalTypeShort, "@ФормДовер": PoaLegalForm, "@ДатаВыдДовер": Date, "@СрокДейст": Date, origin_poa_num: String1_50 | null, revoc_poa_num: String1_50 | null, origin_poa_mchd_num: BoxUuid | null, revoc_poa_mchd_num: BoxUuid | null, origin_poa_notar_num: String1_28 | null, revoc_poa_notar_num: String1_28 | null, origin_principal: Array<InitPrincipalWrap>, notary: Notary | null, acting_notary: ActingNotary | null, };
