// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompInn } from "./CompInn";
import type { Kpp } from "./Kpp";
import type { PersInn } from "./PersInn";
import type { String1_50 } from "./String1_50";

export type PasswordDataClientShort = { nick: String1_50, password: string, pers_inn: PersInn, comp_inn: CompInn, kpp: Kpp, };
