// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdrWrap } from "./AdrWrap";
import type { Date } from "./Date";
import type { Email } from "./Email";
import type { Fio } from "./Fio";
import type { Gender } from "./Gender";
import type { PassportRf } from "./PassportRf";
import type { Phone } from "./Phone";
import type { Snils } from "./Snils";

export type PersonMetadata = { snils: Snils, fio: Fio, passport: PassportRf | null, address: AdrWrap | null, gender: Gender | null, birth_day: Date | null, phone: Phone | null, email: Email | null, };
