// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { Digits2_2 } from "./Digits2_2";
import type { String1_25 } from "./String1_25";
import type { String1_4000 } from "./String1_4000";
import type { String7_7 } from "./String7_7";

export type PersonDocums = { "@КодВидДок": Digits2_2, "@СерНомДок": String1_25, "@ДатаДок": Date, "@ВыдДок": String1_4000 | null, "@КодВыдДок": String7_7 | null, expDate: Date | null, };
