// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { Date } from "./Date";
import type { Digits4_4 } from "./Digits4_4";
import type { IrrevocablePoa } from "./IrrevocablePoa";
import type { PoaTypeRedelegatable } from "./PoaTypeRedelegatable";
import type { PoaTypeRevocable } from "./PoaTypeRevocable";
import type { String1_1000 } from "./String1_1000";
import type { String1_28 } from "./String1_28";
import type { String1_50 } from "./String1_50";

export type PoaMetadata = { "@ВидДовер": PoaTypeRevocable, "@ПрПередов": PoaTypeRedelegatable, "@ВнНомДовер": String1_50, "@НомДовер": BoxUuid, "@НомРНДДовер": String1_28 | null, "@ДопИдДовер": String1_50 | null, "@ДатаВнРегДовер": Date | null, "@ДатаВыдДовер": Date, "@СрокДейст": Date, "@КодНО": Digits4_4 | null, tax_org_idents: Array<Digits4_4>, СведСист: String1_1000, Безотзыв: IrrevocablePoa | null, };
