// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DerivedPoa } from "./DerivedPoa";
import type { RootPoa } from "./RootPoa";

export type PoaRootKind = { "Довер": RootPoa } | { "Передов": DerivedPoa };
