// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Digits7_7 } from "./Digits7_7";
import type { PoaRootKind } from "./PoaRootKind";

export type PoaWrap = { "@КНД": Digits7_7 | null, $value: PoaRootKind, };
