// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoaRootKind } from "./PoaRootKind";
import type { String7_7 } from "./String7_7";

export type PoaWrap = { "@КНД": String7_7 | null, $value: PoaRootKind, };
