// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flag } from "./Flag";
import type { LegalRep } from "./LegalRep";
import type { ParticipantStatus } from "./ParticipantStatus";
import type { PersInn } from "./PersInn";
import type { PersonMchd } from "./PersonMchd";
import type { Snils } from "./Snils";
import type { String1_255 } from "./String1_255";

export type PrincipalPerson = { "@СтУчНД": ParticipantStatus | null, "@ПрДеесп": Flag | null, "@ПрНалРук": Flag | null, "@ДокНедеесп": String1_255 | null, "@ИННФЛ": PersInn | null, "@СНИЛС": Snils, СведФЛ: PersonMchd, СвЗакПредРук: LegalRep | null, };
