// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignOrgPrincipal } from "./ForeignOrgPrincipal";
import type { Ip } from "./Ip";
import type { PrincipalPerson } from "./PrincipalPerson";
import type { RussOrgPrincipal } from "./RussOrgPrincipal";

export type Principal = { РосОргДовер: RussOrgPrincipal | null, ИнОргДовер: ForeignOrgPrincipal | null, ИПДовер: Ip | null, ФЛДовер: PrincipalPerson | null, };
