// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegateInfo } from "./DelegateInfo";
import type { DelegatePowers } from "./DelegatePowers";
import type { Flag } from "./Flag";
import type { NotarialCertification } from "./NotarialCertification";
import type { OriginalPoa } from "./OriginalPoa";
import type { PoaMetadata } from "./PoaMetadata";
import type { SubPrincipal } from "./SubPrincipal";

export type RedelegatedPoa = { "@ПрНалПередов": Flag, СвПервДовер: OriginalPoa, СвПередов: OriginalPoa | null, СвПереДовер: PoaMetadata, СвПередПолн: Array<SubPrincipal>, СвПолучПолн: Array<DelegateInfo>, СвПолн: DelegatePowers, СвНотУд: NotarialCertification | null, };
