// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flag } from "./Flag";
import type { PersInn } from "./PersInn";
import type { PrincipalNotarialStatus } from "./PrincipalNotarialStatus";
import type { Snils } from "./Snils";
import type { WrapPerson } from "./WrapPerson";

export type RedelegatePerson = { "@СтУчНД": PrincipalNotarialStatus | null, "@ПрНалРук": Flag | null, "@ИННФЛ": PersInn, "@СНИЛС": Snils, СведРукоп: WrapPerson | null, СведФЛ: WrapPerson, };
