// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flag } from "./Flag";
import type { JuridicalWrapPerson } from "./JuridicalWrapPerson";
import type { ParticipantStatus } from "./ParticipantStatus";
import type { PersInn } from "./PersInn";
import type { Snils } from "./Snils";

export type RedelegatePerson = { "@СтУчНД": ParticipantStatus | null, "@ПрНалРук": Flag | null, "@ИННФЛ": PersInn, "@СНИЛС": Snils, СведРукоп: JuridicalWrapPerson | null, СведФЛ: JuridicalWrapPerson, };
