// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JuridicalWrapPerson } from "./JuridicalWrapPerson";
import type { RussOrganization } from "./RussOrganization";

export type RedelegaterFilial = { СвФил: RussOrganization, СвРукФил: JuridicalWrapPerson, };
