// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Password } from "./Password";

export type RegistrationData = { password: Password, jsonFilePath: string, signFilePath: string, };
