// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpPrincipal } from "./IpPrincipal";
import type { ManagementType } from "./ManagementType";
import type { PrimeManagerOrg } from "./PrimeManagerOrg";
import type { WrapPerson } from "./WrapPerson";

export type RootManager = { "@ПолнЮЛ": ManagementType, СВЮЛ: PrimeManagerOrg | null, СвФЛ: WrapPerson | null, СвИП: IpPrincipal | null, };
