// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegateInfo } from "./DelegateInfo";
import type { DelegatePowers } from "./DelegatePowers";
import type { NotarialCertification } from "./NotarialCertification";
import type { PoaMetadata } from "./PoaMetadata";
import type { PrincipalInfo } from "./PrincipalInfo";

export type RootPoa = { СвДов: PoaMetadata, СвДоверит: Array<PrincipalInfo>, СвУпПред: Array<DelegateInfo>, СвПолн: DelegatePowers, СвНотУд: NotarialCertification | null, };
