// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompInn } from "./CompInn";
import type { DirectAuthorityDoc } from "./DirectAuthorityDoc";
import type { Kpp } from "./Kpp";
import type { Ogrn } from "./Ogrn";
import type { ParticipantStatus } from "./ParticipantStatus";
import type { Phone } from "./Phone";
import type { PostalAddress } from "./PostalAddress";
import type { String1_1000 } from "./String1_1000";
import type { String1_80 } from "./String1_80";
import type { String3_129 } from "./String3_129";

export type RussOrganization = { "@СтУчНД": ParticipantStatus | null, "@НаимОрг": String1_1000, "@ИННЮЛ": CompInn | null, "@КПП": Kpp, "@ОГРН": Ogrn | null, "@РегНомер": String1_80 | null, "@НаимУчрДок": String1_1000 | null, "@КонтактТлф": Phone | null, "@АдрЭлПочт": String3_129 | null, ДокПдтв: DirectAuthorityDoc | null, АдрРег: PostalAddress | null, };
