// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fio } from "./Fio";
import type { String1_16000 } from "./String1_16000";

export type Signature = { ХешPDFДок: String1_16000, ПодпИзобр: String1_16000, ХешПодп: String1_16000, ДатаВремПодп: bigint, ФИООтв: Fio, };
