// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignOrgPrincipal } from "./ForeignOrgPrincipal";
import type { IpPrincipal } from "./IpPrincipal";
import type { RedelegatePerson } from "./RedelegatePerson";
import type { RedelegaterFilial } from "./RedelegaterFilial";
import type { RussOrgPrincipal } from "./RussOrgPrincipal";

export type SubPrincipalInfo = { РосОргПерПолн: RussOrgPrincipal | null, ИППерПолн: IpPrincipal | null, ФЛПерПолн: RedelegatePerson | null, ФилПерПолн: RedelegaterFilial | null, ИнПерПолн: ForeignOrgPrincipal | null, };
