// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { DateTime } from "./DateTime";

export type User = { user_id: BoxUuid, mchd_tax_guid: BoxUuid | null, mchd_tax_file: string | null, mchd_home_guid: BoxUuid | null, mchd_home_file: string | null, last_update: DateTime, };
