// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectAuthorityDoc } from "./DirectAuthorityDoc";
import type { PersInn } from "./PersInn";
import type { PersonMchd } from "./PersonMchd";
import type { PrincipalNotarialStatus } from "./PrincipalNotarialStatus";
import type { Snils } from "./Snils";
import type { String1_255 } from "./String1_255";

export type WrapPerson = { principal_notarial_status: PrincipalNotarialStatus | null, inn: PersInn | null, snils: Snils | null, position: String1_255 | null, direct_authority_doc: DirectAuthorityDoc | null, СведФЛ: PersonMchd, };
