services:
  db:
    image: postgres:16-alpine
    container_name: fin_app_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fin_app_server
    ports:
      - "5432:5432"
    volumes:
      - fin_app_server_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fin_app_server"]
      interval: 5s
      timeout: 5s
      retries: 5

  crypto-service:
    build:
      context: .
      dockerfile: crates/crypto_service/DockerFile
      args:
        - CRATE_NAME=crypto_service

    container_name: crypto_service
    restart: always
    ports:
      - "8081:8081"

    environment:
      - CRYPTCP_PATH=/opt/cprocsp/bin/amd64/cryptcp
      - RUST_LOG=info
      - PORT=8081

    depends_on:
      db:
        condition: service_healthy

volumes:
  fin_app_server_data: