// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthStep } from "./AuthStep";
import type { PasswordDataClientShort } from "./PasswordDataClientShort";
import type { RegFilesPathData } from "./RegFilesPathData";
import type { RegInitData } from "./RegInitData";

export type AuthTSRS = { auth_step: AuthStep, passw_data: PasswordDataClientShort, reg_init_data: RegInitData, reg_files_data: RegFilesPathData, };
