// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { String1_255 } from "./String1_255";

export type ConfineValue = { "КодЗначОгр": String1_255 } | { "ТексЗначОгр": String1_255 };
