// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignOrg } from "./ForeignOrg";
import type { IpPrincipal } from "./IpPrincipal";
import type { RussOrganization } from "./RussOrganization";
import type { WrapPerson } from "./WrapPerson";

export type Delegate = { organization: RussOrganization | null, ip: IpPrincipal | null, person: WrapPerson | null, filial: RussOrganization | null, foreign_organization: ForeignOrg | null, };
