// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatePowers } from "./DelegatePowers";
import type { DelegateWrap } from "./DelegateWrap";
import type { Flag } from "./Flag";
import type { NotarialCertification } from "./NotarialCertification";
import type { OriginalPoa } from "./OriginalPoa";
import type { PoaMetadata } from "./PoaMetadata";
import type { SubPrincipal } from "./SubPrincipal";

export type DerivedPoa = { "@ПрНалПередов": Flag, СвПервДовер: OriginalPoa, prev_poa: OriginalPoa | null, СвПереДовер: PoaMetadata, СвПередПолн: Array<SubPrincipal>, СвПолучПолн: Array<DelegateWrap>, СвПолн: DelegatePowers, notary_sertification: NotarialCertification | null, };
