// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FnsReportType = "Декларация УСН (Доходы 6%)" | "Декларация УСН (Доходы - Расходы 15%)" | "Уведомление УСН (Доходы 6%)" | "Уведомление УСН (Доходы - Расходы 15%)";
