// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompInn } from "./CompInn";
import type { Digits3_3 } from "./Digits3_3";
import type { Kpp } from "./Kpp";
import type { Phone } from "./Phone";
import type { PostalAddress } from "./PostalAddress";
import type { PrincipalNotarialStatus } from "./PrincipalNotarialStatus";
import type { String11_11 } from "./String11_11";
import type { String1_1000 } from "./String1_1000";
import type { String1_255 } from "./String1_255";
import type { String1_80 } from "./String1_80";
import type { String3_129 } from "./String3_129";

export type ForeignOrg = { principal_notarial_status: PrincipalNotarialStatus | null, "@НаимИО": String1_1000, inn: CompInn | null, kpp: Kpp | null, nza: String11_11 | null, country_code: Digits3_3 | null, reg_org_name: String1_255 | null, reg_number: String1_80 | null, foreign_tax_id: String1_80 | null, tel_number: Phone | null, email: String3_129 | null, foreign_address: String1_1000 | null, russian_address: PostalAddress | null, };
