// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompStatus } from "./CompStatus";

export type IsCompActive = { status: CompStatus | null, code: string | null, };
