// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomePowerInfo } from "./HomePowerInfo";
import type { MchdStep } from "./MchdStep";
import type { MchdType } from "./MchdType";
import type { Доверенность } from "./Доверенность";

export type MchdTSRS = { mchd_step: MchdStep, poa_mchd: Доверенность, mchd_type: MchdType, home_power_info: HomePowerInfo, };
