// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { Currency } from "./Currency";
import type { Date } from "./Date";
import type { DocNum } from "./DocNum";
import type { Integ } from "./Integ";
import type { RubF } from "./RubF";

export type NewContrData = { ctrpty_id: BoxUuid, contract_num: DocNum, contract_date: Date, contract_title: string, contract_st_date: Date, contract_end_date: Date, contract_currency: Currency, contract_tot_amnt: RubF, contract_def_days: Integ, contract_descr: string, };
