// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flag } from "./Flag";
import type { PersInn } from "./PersInn";
import type { PersonMchd } from "./PersonMchd";
import type { PrincipalNotarialStatus } from "./PrincipalNotarialStatus";
import type { RootManager } from "./RootManager";
import type { Snils } from "./Snils";
import type { String1_255 } from "./String1_255";

export type PersonPrincipal = { "@СтУчНД": PrincipalNotarialStatus | null, legal_capacity: Flag | null, assistant_signatory: Flag | null, incapacity_proof_doc: String1_255 | null, inn: PersInn | null, "@СНИЛС": Snils, СведФЛ: PersonMchd, root_manager: RootManager | null, };
