// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { Digits12_12 } from "./Digits12_12";
import type { Digits3_3 } from "./Digits3_3";
import type { Fio } from "./Fio";
import type { Gender } from "./Gender";
import type { IsCitizen } from "./IsCitizen";
import type { PersonDocum } from "./PersonDocum";
import type { Phone } from "./Phone";
import type { PostalAddress } from "./PostalAddress";
import type { String1_250 } from "./String1_250";
import type { String3_129 } from "./String3_129";

export type PersonMchd = { gender: Gender | null, is_citizen: IsCitizen | null, ern_num: Digits12_12 | null, birth_day: Date | null, birth_place: String1_250 | null, country_code: Digits3_3 | null, tel_number: Phone | null, email: String3_129 | null, ФИО: Fio, address: PostalAddress | null, person_docums: PersonDocum | null, };
