// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bic } from "./Bic";
import type { RasAcc } from "./RasAcc";

export type RasBicAcc = { bic: Bic, ras_acc: RasAcc, };
