// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { CompInn } from "./CompInn";
import type { Email } from "./Email";
import type { FirstName } from "./FirstName";
import type { Kpp } from "./Kpp";
import type { MidName } from "./MidName";
import type { Password } from "./Password";
import type { PersInn } from "./PersInn";
import type { Phone } from "./Phone";
import type { Snils } from "./Snils";
import type { SurName } from "./SurName";

export type RegInitData = { surName: SurName, firstName: FirstName, midName: MidName | null, persInn: PersInn, snils: Snils, compInn: CompInn, kpp: Kpp, phone: Phone, email: Email, password: Password, deviceId: BoxUuid, };
