// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatePowers } from "./DelegatePowers";
import type { DelegateWrap } from "./DelegateWrap";
import type { NotarialCertification } from "./NotarialCertification";
import type { PoaMetadata } from "./PoaMetadata";
import type { PrincipalWrap } from "./PrincipalWrap";

export type RootPoa = { СвДов: PoaMetadata, СвДоверит: Array<PrincipalWrap>, СвУпПред: Array<DelegateWrap>, СвПолн: DelegatePowers, notarial_certification: NotarialCertification | null, };
