// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompInn } from "./CompInn";
import type { CompanyName } from "./CompanyName";
import type { DirectAuthorityDoc } from "./DirectAuthorityDoc";
import type { Kpp } from "./Kpp";
import type { Ogrn } from "./Ogrn";
import type { Phone } from "./Phone";
import type { PostalAddress } from "./PostalAddress";
import type { PrincipalNotarialStatus } from "./PrincipalNotarialStatus";
import type { String1_1000 } from "./String1_1000";
import type { String1_80 } from "./String1_80";
import type { String3_129 } from "./String3_129";

export type RussOrganization = { principal_notarial_status: PrincipalNotarialStatus | null, "@НаимОрг": CompanyName, comp_inn: CompInn | null, "@КПП": Kpp, ogrn: Ogrn | null, reg_num: String1_80 | null, founding_doc: String1_1000 | null, phone: Phone | null, email: String3_129 | null, direct_authority_doc: DirectAuthorityDoc | null, address: PostalAddress | null, };
