// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { DateTime } from "./DateTime";
import type { MchdPower } from "./MchdPower";

export type User = { user_id: BoxUuid, guids: Array<BoxUuid>, powers: { [key in BoxUuid]?: Array<MchdPower> }, last_update: DateTime, };
