// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressData } from "./AddressData";

export type AdrWrap = { short_dada_address: string | null, full_dada_address: string | null, address_data: AddressData | null, };
