// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { CompInn } from "./CompInn";
import type { CompStatus } from "./CompStatus";
import type { CompType } from "./CompType";
import type { CtrprtyMetadata } from "./CtrprtyMetadata";
import type { DateTime } from "./DateTime";
import type { Kpp } from "./Kpp";

export type Company = { comp_id: BoxUuid, comp_inn: CompInn, kpp: Kpp, comp_type: CompType, comp_status: CompStatus, metadata: CtrprtyMetadata, last_update: DateTime, };
