// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FirstName } from "./FirstName";
import type { MidName } from "./MidName";
import type { SurName } from "./SurName";

export type Fio = { "@Фамилия": SurName, "@Имя": FirstName, "@Отчество": MidName | null, };
