// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Operation } from "./Operation";
import type { OperationInfo } from "./OperationInfo";
import type { OperationRaw } from "./OperationRaw";

export type OperationStep = { "AccessDenied": { text: OperationInfo, } } | { "Loading": { text: OperationInfo, } } | { "SuccessRaw": { text: OperationInfo, operations: Array<OperationRaw>, } } | { "Success": { operations: Array<Operation>, } } | { "TryLater": { text: OperationInfo, } };
