// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { PasspRfCode } from "./PasspRfCode";
import type { PasspRfNumber } from "./PasspRfNumber";
import type { String1_4000 } from "./String1_4000";
import type { String7_7 } from "./String7_7";

export type PassportRf = { doc_code: PasspRfCode, doc_ser_num: PasspRfNumber, doc_date: Date | null, issued_by: String1_4000 | null, issued_code: String7_7 | null, exp_date: Date | null, };
