// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PoaReqElemsFlag = "00000000" | "01000000" | "00100000" | "00010000" | "01100000" | "00110000" | "01110000";
