// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RussOrganization } from "./RussOrganization";
import type { WrapPerson } from "./WrapPerson";

export type RedelegaterFilial = { СвФил: RussOrganization, СвРукФил: WrapPerson, };
