// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxUuid } from "./BoxUuid";
import type { SessionUser } from "./SessionUser";

export type SessionUserToken = { user: SessionUser, token: BoxUuid, };
