// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Company } from "./Company";
import type { Person } from "./Person";
import type { User } from "./User";

export type SessionUser = { user: User, person: Person, company: Company, };
