[package]
name = "mobile"
version = "0.1.0"
description = "fin-app"
authors = [""]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"


[lib]
name = "mobile"
crate-type = ["rlib"]
path = "src/lib.rs"

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
shared_lib = { workspace = true, features= ['client'] }

blake3 = { workspace = true }

chrono = { workspace = true }

directories = { workspace = true }

dotenvy = { workspace = true }

encoding_rs = { workspace = true }

futures = { workspace = true }

keyring = { workspace = true }

log = { workspace = true }

machine-uid = { workspace = true }

quick-xml = { workspace = true }

reqwest = { workspace = true, features = ["json", "rustls", "query", "cookies", "form"] }
reqwest-middleware = { workspace = true, features = ["json", "query"]  }
reqwest-retry = { workspace = true }



serde = { workspace = true }
serde_json = { workspace = true }

sqlx = { workspace = true, features = ["sqlite"] }

tauri = { workspace = true, features = [] }
tauri-plugin-dialog = { workspace = true }
tauri-plugin-shell = { workspace = true }
tauri-plugin-log = { workspace = true }
tauri-plugin-fs = { workspace = true}

tokio = { workspace = true }

toml = { workspace = true }

ts-rs = { workspace = true }

uuid = { workspace = true, features = ["v5"] }

