[network]
inst_conn_timeout = 1
inst_tot_timeout = 2
inst_request_interval = 1
inst_retries = 3
inst_poll_intervals = 1

std_conn_timeout = 5
std_tot_timeout = 10
std_request_interval = 2
std_retries = 5
std_poll_intervals = 4

rel_conn_timeout = 10
rel_tot_timeout = 60
rel_request_interval = 3
rel_retries = 3
rel_poll_intervals = 10

[dadata]
dadata_comp_url = "https://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party"
dadata_adr_paid_url = "https://cleaner.dadata.ru/api/v1/clean/address"

[smsru]
call_add_url = "https://sms.ru/callcheck/add"
get_stat_url = "https://sms.ru/callcheck/status"

[email_sender]
base_url = "https://api.resend.com/emails"
from = "Security <onboarding@resend.dev>"