[network]
inst_conn_timeout = 1000
inst_tot_timeout = 2500
inst_request_interval = 500
inst_retries = 1

std_conn_timeout = 3000
std_tot_timeout = 6000
std_request_interval = 1000
std_retries = 1

inst_poll_intervals = 4000
std_poll_intervals = 10000

[dadata]
dadata_comp_url = "https://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party"
dadata_adr_paid_url = "https://cleaner.dadata.ru/api/v1/clean/address"

[smsru]
call_add_url = "https://sms.ru/callcheck/add"
get_stat_url = "https://sms.ru/callcheck/status"

[email_sender]
base_url = "https://api.resend.com/emails"
from = "Security <onboarding@resend.dev>"

[postgresql_options]
fast_max_conn = 15
fast_timeout = 800
long_max_conn = 5
long_timeout = 15000