// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DocType = "bank_order" | "payment_order" | "payment_claim" | "collection_order" | "bank_statement" | "cash_receipt" | "cash_voucher" | "cash_check" | "waybill_torg12" | "upd" | "transport_waybill" | "acceptance_act" | "service_act" | "vat_invoice" | "payment_invoice" | "reconciliation_act" | "accounting_note" | "write_off_act" | "correction_act" | "other";
