// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationInfo } from "./OperationInfo";
import type { OperationRaw } from "./OperationRaw";

export type OperationStep = { "AccInput": { text: OperationInfo, } } | { "Loading": { text: OperationInfo, } } | { "ManualInput": { text: OperationInfo, } } | { "NewBankAcc": { text: OperationInfo, } } | { "ProcessSuccess": { text: OperationInfo, count: number, } } | { "StatementLoader": { text: OperationInfo, } } | { "StatementSuccess": { text: OperationInfo, operations: Array<OperationRaw>, } } | { "TryLater": { text: OperationInfo, } };
