// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { ContractOption } from "./ContractOption";
import type { DocType } from "./DocType";
import type { Operation } from "./Operation";
import type { OperationInfo } from "./OperationInfo";
import type { OperationRaw } from "./OperationRaw";
import type { OperationStep } from "./OperationStep";

export type OperationTSTS = { operation_raw: OperationRaw, operation: Operation, contract_option: ContractOption, doc_type: DocType, account: Account, oper_step: OperationStep, oper_inf: OperationInfo, };
