// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FnsReportType } from "./FnsReportType";
import type { ReportInfo } from "./ReportInfo";
import type { ReportStep } from "./ReportStep";

export type ReportTSTS = { report_step: ReportStep, report_info: ReportInfo, fns_report_type: FnsReportType, };
