// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpPrincipal } from "./IpPrincipal";
import type { ManagementType } from "./ManagementType";
import type { PrimeManagerOrg } from "./PrimeManagerOrg";
import type { WrapPerson } from "./WrapPerson";

export type RootManager = { "@ПолнЮЛ": ManagementType, prime_manager_org: PrimeManagerOrg | null, prime_manager_person: WrapPerson | null, prime_manager_ip: IpPrincipal | null, };
